### ISSUE TITLE
Coverage not working

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/pybamm-cookie#61]
I cloned the project recently and the coverage was not working as the action did not find any file to push. I found a way to fix it (probably not ideal, see https://github.com/mmsg-warwick/encapsulated-LTES/pull/4).

**Comment by agriyakhetarpal** [comment]
Yes, I think this is because while the posargs are passed to the coverage session:

```python
  session.posargs.append("--cov=src/encapsulated_ltes")
  session.posargs.append("--cov-report=xml")
  run_user_tests(session)
```

the `run_user_tests` session does not accept them, so they are silently ignored.

I think it's better to return to individual sessions and explicit dependency installations/commands, even at the cost of some code duplication.
